### ISSUE TITLE
How to use static lib file?

### ISSUE THREAD

**Issue by fwx5618177** [nflvic/zcon#1]
Maybe we need to add a header file as the build files?

**Comment by nflvic** [comment]
Please refer to this example. https://github.com/nflvic/sql_example
Note that it depends on mysql c-api-8.0

**Comment by fwx5618177** [comment]
> Please refer to this example. https://github.com/nflvic/sql_example Note that it depends on mysql c-api-8.0

Maybe need to update the doc? Let me do this when I go through all test cases.

**Comment by nflvic** [comment]
I have updated the readme with valid examples

**Comment by nflvic** [comment]
> > Please refer to this example. https://github.com/nflvic/sql_example Note that it depends on mysql c-api-8.0
> 
> Maybe need to update the doc? Let me do this when I go through all test cases.

I have updated the readme with valid examples
